/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg9.pkg3.pkg1;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author fedora
 */
public class NewJFrame extends javax.swing.JFrame {

    public class MyPicture extends JPanel {
        Graphics2D canvas;
        BufferedImage buff;
        int x = 400;
        int y = 250;
        
        MyPicture() {
            buff = new BufferedImage(x, y, BufferedImage.TYPE_INT_RGB);
            canvas = (Graphics2D) buff.getGraphics();
            canvas.setPaint(Color.GRAY);
            canvas.fillRect(0, 0, x, y);
            canvas.setPaint(Color.BLACK);
            canvas.drawOval(100, 80, 90, 90);
            canvas.drawArc(100, 115, 90, 30, 180, 180);
            canvas.drawOval(140, 70, 10, 10);
            canvas.drawOval(140, 170, 10, 10);
            canvas.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 40));
            canvas.drawString("Java!", 85, 50);
            try {
                fill(110, 110, Color.GRAY, Color.WHITE);
                fill(140, 150, Color.GRAY, Color.RED);
                fill(145, 75, Color.GRAY, Color.RED);
                fill(145, 175, Color.GRAY, Color.WHITE);
            } catch (Exception ex) {
            }
        }
        
        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(buff, 0, 0, this);            
        }
        
        private void fill(int x, int y, Color bgcolor, Color color) throws Exception {
            ArrayList<Point> point = new ArrayList<>();
            point.add(new Point(x, y));
            Color oldColor = canvas.getColor();
            canvas.setPaint(color);
            while (point.size() > 0) {
                Point p = point.remove(0);
                x = p.x; y = p.y;
                if (bgcolor.getRGB() == buff.getRGB(x, y)) {
                    canvas.drawLine(x, y, x, y);
                    point.add(new Point(x+1, y));
                    point.add(new Point(x-1, y));
                    point.add(new Point(x, y+1));
                    point.add(new Point(x, y-1));
                }
            }
            
            canvas.setPaint(oldColor);
            repaint();
        }
    }
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new MyPicture();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 250);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
