/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg8.pkg3.pkg1.pkg1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fedora
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Pazdr = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Gel = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Fam = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane_Pozdr = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_Pazdr.setText("jButton_Pazdr");
        jButton_Pazdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PazdrActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Pazdr);
        jButton_Pazdr.setBounds(470, 30, 150, 25);

        jTextArea_Gel.setColumns(20);
        jTextArea_Gel.setLineWrap(true);
        jTextArea_Gel.setRows(5);
        jTextArea_Gel.setText("счастья\nудачи\nздоровья\nрадости");
        jScrollPane2.setViewportView(jTextArea_Gel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 223, 78);

        jTextArea_Fam.setColumns(20);
        jTextArea_Fam.setLineWrap(true);
        jTextArea_Fam.setRows(5);
        jTextArea_Fam.setText("Иванов\nСмирнов\nСидоров");
        jScrollPane3.setViewportView(jTextArea_Fam);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(240, 10, 223, 78);

        jEditorPane_Pozdr.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane_Pozdr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 620, 180);

        setSize(new java.awt.Dimension(639, 326));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PazdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PazdrActionPerformed
        ArrayList<String> pozdr = new ArrayList<>();
        ArrayList<String> fam = new ArrayList<>();

        jEditorPane_Pozdr.setText(null);

        try {
            for (int i = 0; i < jTextArea_Gel.getLineCount(); i++) {
                int end = jTextArea_Gel.getLineEndOffset(i);
                int start = jTextArea_Gel.getLineStartOffset(i);

                if (jTextArea_Gel.getText(start, end - start).trim().equals("")) {
                    continue;
                }

                pozdr.add(jTextArea_Gel.getText(start, end - start).trim());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ошибка чтения пожеланий", "Ошибка чтения", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            for (int i = 0; i < jTextArea_Fam.getLineCount(); i++) {
                int end = jTextArea_Fam.getLineEndOffset(i);
                int start = jTextArea_Fam.getLineStartOffset(i);

                if (jTextArea_Fam.getText(start, end - start).trim().equals("")) {
                    continue;
                }

                fam.add(jTextArea_Fam.getText(start, end - start).trim());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ошибка чтения фамилий", "Ошибка чтения", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (fam.size() > pozdr.size()) {
            JOptionPane.showMessageDialog(rootPane, "Пожеланий на всех не хватит! Уменьшите количество фамилий.", "Ошибка ввода", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StringBuilder s = new StringBuilder("<p align=\"center\"><cite><b><font size=\"5\">");

        try {
            for (int i = 0; i < fam.size(); i++) {
                int p = (int) Math.floor(Math.random() * pozdr.size());
                s.append("Уважаемый <font color=\"990505\">" + fam.get(i) + "</font>" + "! Желаем Вам" + pozdr.get(p).toString().toLowerCase() + "!<br>");
                pozdr.remove(p);
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ошибка генерации поздравления", "Ошибка чтения", JOptionPane.ERROR_MESSAGE);
            s.append("<br>");            
        }        
        jEditorPane_Pozdr.setText(s.toString());
    }//GEN-LAST:event_jButton_PazdrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Pazdr;
    private javax.swing.JEditorPane jEditorPane_Pozdr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_Fam;
    private javax.swing.JTextArea jTextArea_Gel;
    // End of variables declaration//GEN-END:variables
}
