/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg8.pkg3.pkg1;

/**
 *
 * @author fedora
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1_2 = new javax.swing.JButton();
        jButton1_3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 380, 90);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 190, 94, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 120, 380, 19);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(10, 150, 380, 19);

        jButton1_2.setText("jButton1_2");
        jButton1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_2);
        jButton1_2.setBounds(10, 220, 110, 25);

        jButton1_3.setText("jButton1_3");
        jButton1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_3);
        jButton1_3.setBounds(10, 250, 110, 25);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 190, 94, 25);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText("Всё работает!!!");
        jTextArea1.selectAll();
        jTextArea1.copy();
        //jTextArea1.cut();
        //jTextArea1.paste();
        jTextField1.setText(jTextArea1.getSelectedText());
        jTextArea1.replaceSelection("Да!");
        jTextField2.setText(jTextArea1.getText());        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_2ActionPerformed
        try {
            int line = jTextArea1.getLineOfOffset(jTextArea1.getCaretPosition());
            int start = jTextArea1.getLineStartOffset(line);
            int end = jTextArea1.getLineEndOffset(line);
            String s = jTextArea1.getText(start, end - start);
            jTextField1.setText(s);
            jTextArea1.replaceSelection("Yes!");            
        } catch (Exception e) {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jButton1_2ActionPerformed

    private void jButton1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_3ActionPerformed
        try {
        int line_count = jTextArea1.getLineCount() - 1;
        for (int i = 0; i <= line_count; i++) {
            int start = jTextArea1.getLineStartOffset(i);
            int end = jTextArea1.getLineEndOffset(i);
            String s = jTextArea1.getText(start, end - start);
            jTextArea1.replaceRange(Integer.toString(i + 1) + ")" + s, start, end);
        }
        } catch (Exception f) {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jButton1_3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText("");
        jTextArea1.append("Строка 1\n");
        jTextArea1.append("Строка 2\n");
        jTextArea1.append("Строка 3");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_2;
    private javax.swing.JButton jButton1_3;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
