/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg9.pkg3.pkg2;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.geom.Rectangle2D;
import javax.swing.JPanel;

/**
 *
 * @author fedora
 */
public class NewJFrame extends javax.swing.JFrame {

    char[] mas = {'T', 'S', 'E', 'R', 'G', '!'};
    int[] xArray = {20, 40, 60, 80, 100, 120, 130, 140, 280, 332};
    int[] yArray = {350, 345, 340, 310, 290, 280, 275, 273, 271, 269};
    
    public class MyPicture extends JPanel {
        
        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;
            jLabel1.setText("Рисуем!!!");
            this.setBackground(new Color(153, 255, 153));
            this.setForeground(Color.darkGray);
            int w = getWidth(); int h = getHeight();
            GradientPaint gradient = new GradientPaint(0, 0, Color.orange, w, h, Color.green, true);
            g2.setPaint(gradient);
            g2.fillRect(0, 0, w, h);
            g.drawLine(110, 120, 110, 120);
            g.drawLine(20, 20, 360, 20);
            Color oldColor = g.getColor();
            Color newColor = new Color(0, 0, 255);
            g.setColor(newColor);
            g.drawLine(20, 30, 360, 30);
            g.setColor(oldColor);
            g.drawRect(20, 40, 340, 20);
            newColor = new Color(100, 15, 255);
            g.setColor(newColor);
            g.fillRect(80, 80, 50, 15);
            g.setColor(oldColor);
            g.drawRoundRect(20, 70, 340, 30, 20, 15);
            g.drawOval(20, 110, 150, 60);
            g.drawOval(200, 110, 60, 60);
            g.drawArc(280, 110, 80, 60, 0, 180);
            int[] arrayX = {20, 100, 100, 250, 250, 20, 20, 50};
            int[] arrayY = {180, 180, 200, 200, 220, 200, 200, 190};
            Polygon poly = new Polygon(arrayX, arrayY, 8);
            g.drawPolygon(poly);
            Point aPoint = new Point(50, 190);
            if (poly.contains(aPoint)) {
                g.drawString("Yes", 50, 190);
            }
            g.setColor(new Color(10, 200, 55));
            g.fillArc(50, 70, 30, 40, 50, 190);
            newColor = new Color(10, 10, 155);
            g.setColor(newColor);
            Font font = new Font("Tahoma", Font.BOLD | Font.ITALIC, 40);
            Font oldFont = g.getFont();
            g.setFont(font);
            g.drawString("TSN", 270, 220);
            g.setFont(oldFont);
            g.setColor(oldColor);
            
            g.drawLine(20, 220, 20, 350); g.drawLine(20, 350, 360, 350);
            g.drawString("Y", 25, 230); g.drawString("X", 350, 346);
            
            g.setColor(newColor);
            g.drawPolyline(xArray, yArray, 10);
            g.setColor(oldColor);
            g.drawString("y = f(x)", 180, 267);
            
            g2.drawChars(mas, 0, 6, 123, 321);
            
            BasicStroke penl = new BasicStroke(10, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND, 10);
            g2.setStroke(penl);
            g2.draw(new Rectangle2D.Double(350, 50, 50, 50));
        }
    }
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new MyPicture();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 390, 94, 25);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 370);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 380, 260, 20);

        setSize(new java.awt.Dimension(410, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mas[0] = 'x';
        xArray[0] = 10; yArray[0] = 200;
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
